config/routes.rb
Rails.application.routes.draw do
  get 'currency', to: 'currency#first'
  get 'rpi', to: 'rpi#index'
  get 'rest/first'
  get 'rices',to: 'rices#rs'
  get 'parser', to: 'parser#sinatra'
  root 'home#index'
  get 'contacts', to: 'home#contacts'
  get 'projects', to: 'home#projects'
  get 'dezprof', to: 'home#first'
  get 'acc', to: 'home#second'
  get 'nibfeed', to: 'home#third'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/currency_controller.rb
class CurrencyController < ApplicationController
  def first
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def contacts
  end

  def projects
  end

  def first
  end

  def second
  end

  def third
  end
end

app/controllers/parser_controller.rb
class ParserController < ApplicationController
  def sinatra
  end
end

app/controllers/rest_controller.rb
class RestController < ApplicationController
  def first
  end
end

app/controllers/rices_controller.rb
class RicesController < ApplicationController
  def rs
  end
end

app/controllers/rpi_controller.rb
class RpiController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/currency_helper.rb
module CurrencyHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/parser_helper.rb
module ParserHelper
end

app/helpers/rest_helper.rb
module RestHelper
end

app/helpers/rices_helper.rb
module RicesHelper
end

app/helpers/rpi_helper.rb
module RpiHelper
end

app/views/currency/first.html.erb
<div id="about">
<%= image_tag 'c1.png', id: 'myImg' %>
</div>
<div id="about">
  <h2><span class="ec ec-hammer-and-wrench"></span> Что я использовал для этого проекта</h2>
  <p><b>Framework: </b>Ruby on Rails</p>
  <p><b>Database: </b>Postgres</p>
  <p><b>Adapter: </b>Redis</p>
  <p><b>Front: </b>Bootstrap + JQuery</p>
  <p><b>Misc: </b>WebSockets</p>
</div>

<div id="aboutp">
  <h1>Теперь о самой сути проекта</h1>
</div>
<div id="about">
  <p>Данный проект имеет довольно аккуратный интерфейс, где пользователю предложено только наблюдать за скачками валюты в реальном времени.</p>
</div>
<div id="about">
<%= image_tag 'c1.png', id: 'myImg' %>
</div>
<div id="about">
  <p>
  Администратор же может добавлять новые форсированные курсы во вкладочке /admin 
  </p>
</div>
<div id="about">
<%= image_tag 'c2.png', id: 'myImg' %>
</div>
<div id="about">
<%= image_tag 'c3.png', id: 'myImg' %>
</div>
<div id="aboutp">
  <h2>Ссылки</h2>
</div>
<div id="about">
  <a href="https://github.com/daniilty/currency" class="blog-post_cta">github</a>
</div>

app/views/home/contacts.html.erb
<div id="upperco">
  <div id="contacts">
    <h1><span class="ec ec-envelope-with-arrow"></span> Email</h1> 
    <h3> <a class="mail" href="mailto:danya.toreev@mail.ru">danya.toreev@mail.ru</a><h3>
  </div>
  <div id="contacts">
    <h1><span class="ec ec-telephone-receiver"></span> Телефон</h1>
    <h3><a class="mail" href="tel:89373755988">+79373755988</a></h3>
  </div>
  </div>

app/views/home/first.html.erb
<div id="about">
<%= image_tag 'd1.png', id: 'myImg' %>
</div>
<div id="about">
  <h2><span class="ec ec-hammer-and-wrench"></span> Что я использовал для этого проекта</h2>
  <p><b>Framework: </b>Ruby on Rails</p>
  <p><b>Database: </b>Postgres</p>
  <p><b>Deploy: </b>Capistrano</p>
  <p><b>Authentication: </b>Bcrypt</p>
  <p><b>Image attachment: </b>Shrine</p>
  <p><b>Adapter: </b>Redis</p>
  <p><b>Front: </b>CSS only</p>
  <p><b>Server: </b>Nginx with Passenger</p>
</div>

<div id="aboutp">
  <h1>Теперь о самой сути проекта</h1>
</div>
<div id="about">
  <p> Сайт на первый взгляд может показаться чисто ознакомительным, но в нем, помимо симпатичных картинок имеется написанная с нуля система аутентификации админа и динамическое обновление текущих клиентов и возможность записаться на консультацию у специалиста по телефону или с помощью email(все валидации присутствуют) </p>
</div>
<div id="about">
  <p>
  Аккуратный дизайн и современный стек технологий дают пользователям самый плавный и приятный опыт пользования и точно оставит положительное впечатление о компании
  </p>
</div>

<div id="aboutp">
  <h2>Скриншоты</h2>
</div>

<div id="about">
<%= image_tag 'd2.png', id: 'myImg' %>
</div>
<div id="about">
<%= image_tag 'd3.png', id: 'myImg' %>
</div>
<div id="about">
<%= image_tag 'd4.png', id: 'myImg' %>
</div>
<div id="about">
<%= image_tag 'd5.png', id: 'myImg' %>
</div>
<div id="aboutp">
  <h2>Ссылки</h2>
</div>
<div id="about">
  <a href="https://github.com/daniilty/deza21" class="blog-post_cta">github</a>
  <a href="https://dezprof21.ru" class="blog-post_cta">Сам сайт</a>
</div>

app/views/home/index.html.erb
<div id="uppera">
  <div id="about">
    <h1><span class="ec ec-coffee"></span> Давайте познакомимся</h1>
<p>Здравствуйте! Я Тураев Даниил Андреевич. Имею счастье проживать в Чебоксарах и работать с фреймворком “Ruby on Rails” уже второй год. </p>
  </div>
  <div id="about">
    <h2>
     <span class="ec ec-trophy"></span> Мой технический стек:
    </h2>
    <p><b>•Framework: </b>Ruby on Rails</p>
    <p><b>•DB: </b>Postgres, Mongo</p>
    <p><b>•Deploy: </b>Capistrano</p>
    <p><b>•Frontend: </b>JS, React(not too good;)), CSS</p>
    <p><b>•Pr languages: </b>Ruby(<span class="ec ec-black-heart"></span>), GoLang, C, Java </p>
    <p><b>•Familiar with: </b>Pretty much every Linux distro(Compiled linux core for about 6 times in glorious Gentoo install process)</p>
    <p><b>•Favorite server: </b>Nginx</p>
    <p><b>•Rest api: </b>Sinatra</p>
    <p><b>•Tests: </b>RSpec + Capybara</p>
    <p><b>•Languages: </b>English(Upper-Intermediate), Russian(Native)</p>
  </div>
<div id="about">
    <p>А теперь по порядку)</p> 
  </div>
  <div id="about">
    <p>
    <span class="ec ec-round-pushpin"></span>  Свой путь языковых исканий я начал с C++ в 2017 году, но, из-за того, что я не смог найти ему совершенно никакого применения, кроме олимпиадных задачек, постепенно остыл и перешел на Python. Написав пару простеньких 2д игрушек я опять понял, что мне нужно что-то серьезнее и продолжил поиски в 2018 году. Тут мне удачно подвернулась статья на Хабре, в которой была описана краткая история загадочного фреймворка Ruby on Rails. Я сразу начал искать самоучители, но так как все книги на русском были устаревшими, я решил рискнуть и попробовать изучить книгу Майкла Хартла в оригинале. С того момента я прочитал 3 книги на 1000+ страниц и тонну документации на Github, которую я читаю исключительно на Английском.</p><p>
Помимо Ruby я хорошо владею Java и даже писал простенькие приложения на Android. Для меня не будет проблемой выучить Spring, либо совершенно любой фреймворк для работы(всегда готов пополнить свои знания).
    </p>
  </div>

  <div id="about">
    <h2><span class="ec ec-clipboard"></span> Ключевые навыки:</h2>
    <p><b>•Полная отдача в работе</b></p>
    <p><b>•Дружелюбность</b></p>
    <p><b>•Огромный уровень самомотивации и самоорганизованности</b></p>
    <p><b>•Неутолимая воля к познанию</b></p>
    <p><b>•Знание английского</b></p>
  </div>
  <div id="about">
    <h2><span class="ec ec-hammer-and-wrench"></span> Мои проекты</h2>
    <p>Тут будет несколько демо проектов и один коммерческий(который уже можно посмотреть со своего устройства)</p>
    <%= link_to 'Перейти', projects_url, class: "blog-post_cta" %> 
  </div>
  <div id="about">
    <p> Раз вы все еще здесь, прошу оценить мой rice на gentoo))</p><br>
    <a href="https://www.reddit.com/r/unixporn/comments/gm7zal/dwm_quarantine_drives_me_crazy/"><%= image_tag("rice.png") %></a>
  </div>
</div>

app/views/home/projects.html.erb
<div class="clientsup">
  <div class="clients">
    <div class="client">
      <%= image_tag("c1.png") %>
      <div class="description">
        <h2>Парсер курса доллара</h2>
      <h4>Мой опыт с WebSocket</h4>
        <a class="blog-post_cta" href="<%= currency_url %>">Перейти</a>
      </div>
    </div>
    <div class="client">
      <%= image_tag("r1.png") %>
      <div class="description">
        <h2>Демо сайта для ресторана</h2>
      <h4>Мой опыт с тестами и REST</h4>
        <a class="blog-post_cta" href="<%= rest_first_url %>">Перейти</a>
      </div>
    </div>
    <div class="client">
      <%= image_tag("d1.png") %>
      <div class="description">
        <h2>Dezprof21</h2>
      <h4>Мой первый коммерческий проект для местной службы дезинфекции
        </h4>
        <a class="blog-post_cta" href="<%= dezprof_url %>">Перейти</a>
      </div>
    </div>
    <div class="client">
      <%= image_tag("s1.jpg") %>
      <div class="description">
        <h2>Account shop</h2>
        <h4>Мой приостановленный пандемией проект</h4>
        <a class="blog-post_cta" href="<%= acc_url %>">Перейти</a>
      </div>
    </div>
    <div class="client">
      <%= image_tag("t1.jpg") %>
      <div class="description">
        <h2>Nibfeed</h2>
        <h4>Мой личный блог</h4>
        <a class="blog-post_cta" href="<%= nibfeed_url %>">Перейти</a>
      </div>
    </div>
    <div class="client">
      <%= image_tag("r1.jpg") %>
      <div class="description">
        <h2>Галерея моих rice'ов</h2>
        <h4>Тут можно ознакомиться с моими кастомизациями разных wm</h4>
        <a class="blog-post_cta" href="<%= rices_url %>">Перейти</a>
      </div>
    </div>
    <div class="client">
      <%= image_tag("p1.jpg") %>
      <div class="description">
        <h2>Sinatra</h2>
        <h4>Демо парсера погоды</h4>
        <a class="blog-post_cta" href="<%= parser_url %>">Перейти</a>
      </div>
    </div>
    <div class="client">
      <%= image_tag("rpi.png") %>
      <div class="description">
        <h2>Мои домашние часы</h2>
      <h4>Или как я посадил на рельсы малину</h4>
        <a class="blog-post_cta" href="<%= rpi_url %>">Перейти</a>
      </div>
    </div>
  </div>
</div>

app/views/home/second.html.erb
<div id="uppera">
  <div id="about">
    <%= image_tag("s1.jpg") %>
  </div>
<div id="about">
  <h2><span class="ec ec-hammer-and-wrench"></span> Что я использовал для этого проекта</h2>
  <p><b>Framework: </b>Ruby on Rails</p>
  <p><b>Database: </b>SQLite3</p>
  <p><b>Deploy: </b>Capistrano</p>
  <p><b>Authentication: </b>Bcrypt</p>
  <p><b>Adapter: </b>Redis</p>
  <p><b>Front: </b>CSS only</p>
  <p><b>Server: </b>Nginx with Passenger</p>
</div>
<div id="aboutp">
  <h1>Идея проекта</h1>
</div>
<div id="about">
  <%= image_tag("s2.jpg")%>
  <p>
  Xочу представить сэмпл интернет магазина по продаже аккаунтов. Есть две роли: продавец и покупатель. Покупатель может спокойно зарегистрироваться через UI,а вот продавцу придётся создать самостоятельную запись в базу данных через консоль с тегом admin: true.</p></div>  
<div id="aboutp">
  <h1>Принцип работы</h1>
</div>
<div id="about">
  <%= image_tag("s3.jpg") %>
  <p>
  Продавец через веб интерфейс добавляет аккаунт, а покупатель, в свою очередь бронирует его через форму</p></div>
<div id="about"><%= image_tag("s4.jpg")%></div>
<div id="about"><%= image_tag("s5.jpg")%></div>
<div id="about">
  <%= image_tag("s6.jpg")%>
  <p>
  Личный кабинет до покупки
  </p>
</div>

<div id="about">
  <%= image_tag("s7.jpg")%>
  <p>
  После
  </p></div>
<div id="about">
  <%= image_tag("s8.jpg")%>
  <p>
  Боковое меню
  </p>
</div>
<div id="about">
  <a class="blog-post_cta" href="https://github.com/daniilty/rails_accounts_shop.git">github</a>
</div>
</div>

app/views/home/third.html.erb
<div id="uppera">
  <div id="about">
    <%= image_tag("t1.jpg") %>
  </div>
  <div id="about">
  <h2><span class="ec ec-hammer-and-wrench"></span> Что я использовал для этого проекта</h2>
  <p><b>Framework: </b>Ruby on Rails</p>
  <p><b>Database: </b>SQLite3</p>
  <p><b>Deploy: </b>Capistrano</p>
  <p><b>Authentication: </b>Bcrypt</p>
  <p><b>Image Attachment: </b>ActiveStorage</p>
  <p><b>Adapter: </b>Redis</p>
  <p><b>Front: </b>CSS only</p>
  <p><b>Server: </b>Nginx with Passenger</p>
  </div>
  <div id="aboutp">
    <h1>Краткое описание</h1>
  </div>
  <div id="about">
    <p>Следующим моим проектом был простенький юмористический новостной портал о новостях с Нибиру. Этот проект я запускал на своем Nginx(+ passenger) сервере при помощи гема Capistrano и количество уникальных посетителей было около 400.
Устройство простое: для начала нужно создать аккаунт администратора через консоль и войти в него по пути /adlog
После этого нам открывается возможность добавлять посты и удалять уже существующие.</p>
  </div>
  <div id="aboutp">
    <h1>Скриншоты</h1>
  </div>
  <div id="about">
    <%= image_tag("t2.jpg")%>
  </div>
  <div id="about">
    <%= image_tag("t3.jpg")%>
  </div>
  <div id="about">
    <%= image_tag("t4.jpg")%>
  </div>
  <div id="about">
    <%= image_tag("t5.jpg")%>
  </div>
  <div id="about">
    <a class="blog-post_cta" href="https://github.com/daniilty/nibfeed.git">github</a>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Daniilty</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag 'favicon.ico' %>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel='stylesheet' href='https://unpkg.com/emoji.css/dist/emoji.min.css'>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
<header class="header">
  <a href="<%=root_url%>" class="logo"><h2>daniilty</h2></a>
  <a href="https://github.com/daniilty" class="github"><%= image_tag("github.svg")%></a>
  <input class="menu-btn" type="checkbox" id="menu-btn" />
  <label class="menu-icon" for="menu-btn"><span class="navicon"></span></label>
  <ul class="menu">
    <li><a href="<%= projects_url %>">Проекты</a></li>
    <li><a href="<%= contacts_url %>">Контакты</a></li>
  </ul>
</header>
  <body>
    <%= yield %>
  </body>
</html>

app/views/parser/sinatra.html.erb
<div id="about">
<%= image_tag 'p1.jpg' %>
</div>
<div id="about">
<%= image_tag 'p2.jpg' %>
</div>
<div id="about">
<h1><span class="ec ec-hammer-and-wrench"></span> Гемы:</h1>
  <p><b>Sinatra</b></p>
  <p><b>HTTParty</b></p>
  <p><b>Nokogiri</b></p>
  <p><b>Rest-Client</b></p>
</div>
<div id="aboutp">
  <h1>Описание</h1>
</div>
<div id="about">
<p>Также, я когда-то учил sinatra, но в реальных проектах ее применить не было возможности. В качестве примера хочу привести простенький парсер погоды с Гисметео.</p>
</div>
<div id="about">
  <a href="https://github.com/daniilty/sinatra_sample.git" class="blog-post_cta">github</a>
</div>

app/views/rest/first.html.erb
<div id="about">
  <%= image_tag("r1.png") %>
  <p>Этот проект пусть и выглядит не особо привлекательно, но скрывает под капотом довольно неплохой технический стек.</p>
</div>
<div id="about">
  <h2><span class="ec ec-hammer-and-wrench"></span> Что я использовал для этого проекта</h2>
  <p><b>Framework: </b>Ruby on Rails</p>
  <p><b>Database: </b>Postgres</p>
  <p><b>Deploy: </b>Heroku</p>
  <p><b>Encryption: </b>JWT</p>
  <p><b>Image attachment: </b>Shrine</p>
  <p><b>Adapter: </b>Redis</p>
  <p><b>Front: </b>Bootstrap</p>
  <p><b>Test: </b>RSpec + Capybara</p>
</div>
<div id="aboutp">
  <h1>Теперь о самой сути проекта</h1>
</div>
<div id="about">
  <p>Это демо сайта для ресторана. Есть две роли: Посетитель и администратор. Посетитель может просматривать меню за прошедшие дни и заказывать по одному блюду в одной из трех предложенных позиций. Администратор, в свою очередь, может составлять меню в отдельной вкладке. 
  </p>
</div>
<div id="aboutp">
  <h2>Скриншоты</h2>
</div>
<div id="about">
<%= image_tag 'r2.png', id: 'myImg' %>
</div>
<div id="about">
<%= image_tag 'r3 2.png', id: 'myImg' %>
</div>
<div id="about">
<%= image_tag 'r4.png', id: 'myImg' %>
</div>
<div id="about">
<%= image_tag 'r5 2.png', id: 'myImg' %>
</div>
<div id="about">
<%= image_tag 'r6.png', id: 'myImg' %>
</div>
<div id="about">
<%= image_tag 'r7.png', id: 'myImg' %>
</div>
<div id="about">
<%= image_tag 'r8.png', id: 'myImg' %>
</div>
<div id="aboutp">
  <h2>Ссылки</h2>
</div>
<div id="about">
  <a href="https://github.com/daniilty/jetrubyproj" class="blog-post_cta">github</a>
  <a href="https://whispering-tundra-87656.herokuapp.com/" class="blog-post_cta">Сам сайт</a>
</div>

app/views/rices/rs.html.erb
<div id="about">
  <p>Чтобы доказать свою приверженность святому Unix, прилагаю свои конфигурации различных WM</p>
</div>
<div id="about">
  <%= image_tag 'r1.jpg'%>
</div>
<div id="about">
  <h2><span class="ec ec-hammer-and-wrench"></span> Details</h2>
  <p><b>Distro: </b>Gentoo</p>
  <p><b>WM: </b>DWM</p>
  <p><b>Terminal: </b>Alacritty</p>
  <p><b>Shell: </b>Fish</p>
</div>
<div id="about">
  <%= image_tag 'r2.jpg'%>
</div>
<div id="about">
  <h2><span class="ec ec-hammer-and-wrench"></span> Details</h2>
  <p><b>Distro: </b>Arch</p>
  <p><b>WM: </b>SOWM</p>
  <p><b>Terminal: </b>Alacritty</p>
  <p><b>Shell: </b>Tcsh</p>
</div>
<div id="about">
  <%= image_tag 'r3.png'%>
</div>
<div id="about">
  <h2><span class="ec ec-hammer-and-wrench"></span> Details</h2>
  <p><b>Distro: </b>Gentoo</p>
  <p><b>WM: </b>DWM</p>
  <p><b>Terminal: </b>Alacritty</p>
  <p><b>Shell: </b>Fish</p>
</div>
<div id="about">
  <%= image_tag 'r4.jpg'%>
</div>
<div id="about">
  <h2><span class="ec ec-hammer-and-wrench"></span> Details</h2>
  <p><b>Distro: </b>Debian ARM</p>
  <p><b>WM: </b>DWM</p>
  <p><b>Terminal: </b>st</p>
  <p><b>Shell: </b>zsh</p>
</div>
<div id="about">
  <%= image_tag 'r5.png'%>
</div>
<div id="about">
  <h2><span class="ec ec-hammer-and-wrench"></span> Details</h2>
  <p><b>Distro: </b>Arch</p>
  <p><b>WM: </b>BSPWM</p>
  <p><b>Terminal: </b>Kitty</p>
  <p><b>Shell: </b>Fish</p>
</div>

app/views/rpi/index.html.erb
<div id="about">
<%= image_tag 'rpi.png', id: 'myImg' %>
</div>
<div id="about">
  <h2><span class="ec ec-hammer-and-wrench"></span> Что я использовал для этого проекта</h2>
  <p><b>Framework: </b>Ruby on Rails</p>
  <p><b>Database: </b>Postgres</p>
  <p><b>Deploy: </b>Local deploy with puma</p>
  <p><b>Adapter: </b>Redis</p>
  <p><b>Front: </b>CSS + JS</p>
  <p><b>Job system: </b>Sidekiq</p>
  <p><b>Screen: </b>Cheapest from Aliexpress</p>
  <p><b>Case: </b>Also cheapest from Aliexpress</p>
  <p><b>Hardware: </b>Rpi3b+</p>
  <p><b>OS: </b>Raspbian lite</p>
</div>
<div id="aboutp">
  <h1>Как заставить это работать</h1>
</div>
<div id="about">
  <p>Для начала установим Redis, Postgres, RoR и Chromium на малину:</p>
  <div class="code">
  <p><b>$ </b>sudo apt install postgresql libpq-dev postgresql-client
postgresql-client-common -y</p>
  <p><b>$ </b>sudo systemctl enable postgresql</p>
  <p><b>$ </b>sudo apt-get install redis-server</p>
  <p><b>$ </b>git clone https://github.com/rbenv/rbenv.git ~/.rbenv</p>
  <p><b>$ </b>echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bashrc</p>
  <p><b>$ </b>echo 'eval "$(rbenv init -)"' >> ~/.bashrc</p>
  <p><b>$ </b>git clone https://github.com/rbenv/ruby-build.git ~/.rbenv/plugins/ruby-build</p>
  <p><b>$ </b>echo 'export PATH="$HOME/.rbenv/plugins/ruby-build/bin:$PATH"' >> ~/.bashrc</p>
  <p><b>$ </b>git clone https://github.com/rbenv/rbenv-vars.git ~/.rbenv/plugins/rbenv-vars</p>
  <p><b>$ </b>exec $SHELL</p>
  <p><b>$ </b>rbenv install 2.7.2</p>
  <p><b>$ </b>rbenv global 2.7.2</p>
  <p><b>$ </b>gem install bundler</p>
  <p><b>$ </b>gem install rails</p>
  </div>
  <p> Далее нам остается налить себе чаю, ознакомиться с трудами Иммануила Канта и приступить уже наконец к самой интересной части.</p>
</div>
<div id="about">
  <h2>Устанавливаем остатки</h2>
  <div class="code">
    <p><b>$ </b>sudo apt install xserver-xorg xserver-xorg-video-fbdev xinit pciutils xinput xfonts-100dpi xfonts-75dpi xfonts-scalable </p>
    <p><b>$ </b>vim ~/.bash_profile</p>
    <p><b>[[ -z $DISPLAY && $XDG_VTNR -eq 1 ]] && exec startx</b><p>
    <p><b>:wq</b><p>
  </div>
  <div class="code">
    <p><b>$ </b>git clone https://github.com/daniilty/simple-clock.git</p>
    <p><b>$ </b>cd simple-clock</p>
    <p><b>$ </b>bundle install</p>
    <p><b>$ </b>rails db:create</p>
    <p><b>$ </b>rails db:migrate</p>
    <p><b>$ </b>vim ~/.xinitrc</p>
    <p><b>exec ~/simple-clock/script.sh </b></p>
    <p><b>exec redis-server </b></p>
    <p><b>exec cd ~/simple-clock && bundle exec sidekiq</b></p>
    <p><b>exec cd ~/simple-clock && rails s </b></p>
    <p><b>exec chromium -app=http://127.0.0.1:3000 </b></p>
    <p><b>:wq </b></p>
    <p><b>Alt + Shift + q</b></p>
  </div>
  <p>После релогина у нас откроется хромиум с нашими готовыми часами.</p>
</div>
<div id="aboutp">
  <h1>Ссылки</h1>
</div>
<div id="about">
  <a href="https://github.com/daniilty/simple-clock" class="blog-post_cta">github</a>
  <a href="https://aliexpress.ru/item/4000210928261.html?spm=a2g0o.productlist.0.0.668715096aFL7x&algo_pvid=0d5290ac-d288-4bd2-88b0-c1a6bcecd4e8&algo_expid=0d5290ac-d288-4bd2-88b0-c1a6bcecd4e8-58&btsid=0b8b034116052586121906929e9f34&ws_ab_test=searchweb0_0,searchweb201602_,searchweb201603_" class="blog-post_cta">screen</a>
  <a href="https://aliexpress.ru/item/32965998024.html?spm=a2g0o.productlist.0.0.67c41f2e0sWHcB&algo_pvid=1610b381-da7c-4db9-b3a1-0f067a43df42&algo_expid=1610b381-da7c-4db9-b3a1-0f067a43df42-10&btsid=0b8b034116052585811576389e9f34&ws_ab_test=searchweb0_0,searchweb201602_,searchweb201603_" class="blog-post_cta">Case</a>
</div>